# Generated by Django 3.1.7 on 2021-03-13 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя категории')),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя украшения')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание украшения')),
                ('images', models.CharField(max_length=1000, verbose_name='Изображения')),
                ('stock', models.IntegerField(verbose_name='Количество в наличии')),
                ('complexity', models.IntegerField(verbose_name='Количество дней на новую исполнение новой товарной единицы')),
                ('price_ru', models.FloatField(verbose_name='Цена для СНГ')),
                ('price_en', models.FloatField(verbose_name='Цена для мира')),
                ('create_date', models.DateField(verbose_name='Дата создания позиции')),
                ('category', models.ManyToManyField(blank=True, related_name='jewelry', to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя схемы')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание схемы')),
                ('images', models.CharField(max_length=1000, verbose_name='Изображения')),
                ('urls', models.CharField(max_length=1000, verbose_name='Файлы схемы')),
                ('price_ru', models.FloatField(verbose_name='Цена для СНГ')),
                ('price_en', models.FloatField(verbose_name='Цена для мира')),
                ('create_date', models.DateField(verbose_name='Дата создания позиции')),
                ('category', models.ManyToManyField(blank=True, related_name='pattern', to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('secretCode', models.CharField(max_length=50)),
                ('coints_ru', models.FloatField()),
                ('coints_en', models.FloatField()),
                ('deactivate_date', models.DateField(verbose_name='Дата создания позиции')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_coints_ru', models.FloatField()),
                ('bonus_coints_en', models.FloatField()),
                ('location', models.CharField(max_length=2)),
                ('patterns', models.ManyToManyField(blank=True, to='api.Pattern')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('track_number', models.CharField(max_length=200, verbose_name='Трек отслеживания')),
                ('next_status_date', models.DateField(verbose_name='Примерное время измения статуса')),
                ('jewels', models.ManyToManyField(blank=True, to='api.Jewelry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
                ('patterns', models.ManyToManyField(blank=True, to='api.Pattern')),
            ],
        ),
    ]
