# Generated by Django 3.1.7 on 2021-04-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество показов'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество показов'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='images',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='images',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Изображения'),
        ),
        migrations.CreateModel(
            name='PatternRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Оценка')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='JewelryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Оценка')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jewelry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
