# Generated by Django 3.1.7 on 2021-04-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210406_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='next_status_date',
            field=models.DateField(blank=True, verbose_name='Примерное время измения статуса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Трек отслеживания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bonus_coints_en',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='bonus_coints_ru',
            field=models.FloatField(default=0),
        ),
    ]
