# Generated by Django 3.1.7 on 2021-04-06 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210406_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelryrating',
            name='jewelry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.jewelry'),
        ),
        migrations.AlterField(
            model_name='jewelryrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jewelryRating', to='api.person'),
        ),
        migrations.AlterField(
            model_name='patternrating',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.pattern'),
        ),
        migrations.AlterField(
            model_name='patternrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patternRating', to='api.person'),
        ),
    ]
