# Generated by Django 3.1.7 on 2021-05-09 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210509_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания картинки'),
        ),
    ]
