# Generated by Django 3.1.7 on 2021-05-11 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания картинки'),
        ),
    ]
