# Generated by Django 3.1.7 on 2021-05-25 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210512_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='image',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания картинки'),
        ),
    ]
