# Generated by Django 3.1.7 on 2021-05-29 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210526_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='create_date',
            field=models.DateTimeField(verbose_name='Дата создания позиции'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='next_status_date',
            field=models.DateTimeField(blank=True, verbose_name='Примерное время измения статуса'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания позиции'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='deactivate_date',
            field=models.DateTimeField(verbose_name='Дата создания позиции'),
        ),
    ]
