# Generated by Django 3.1.7 on 2022-01-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_category_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания размера')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создании категории'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='size', to='api.Size'),
        ),
    ]
