# Generated by Django 3.1.7 on 2022-02-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220125_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название файла')),
                ('file', models.FileField(blank=True, upload_to='files/pattern')),
            ],
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='size',
        ),
        migrations.CreateModel(
            name='PatternSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdd', to='api.patternfile')),
                ('jbb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jbb', to='api.patternfile')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.pattern')),
                ('pdf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='api.patternfile')),
                ('png', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='png', to='api.patternfile')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.size')),
            ],
        ),
    ]
