# Generated by Django 3.1.7 on 2022-02-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220213_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternsize',
            name='cdd',
        ),
        migrations.AddField(
            model_name='patternsize',
            name='cbb',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cbb', to='api.patternfile'),
            preserve_default=False,
        ),
    ]
