# Generated by Django 3.1.7 on 2022-03-06 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220219_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternsize',
            name='cbb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbb', to='api.patternfile'),
        ),
        migrations.AlterField(
            model_name='patternsize',
            name='jbb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jbb', to='api.patternfile'),
        ),
        migrations.AlterField(
            model_name='patternsize',
            name='pdf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='api.patternfile'),
        ),
        migrations.AlterField(
            model_name='patternsize',
            name='png',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='png', to='api.patternfile'),
        ),
    ]
