# Generated by Django 3.1.7 on 2022-03-07 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220307_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='name_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Имя схемы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='name_ru',
            field=models.CharField(default='', max_length=200, verbose_name='Имя схемы'),
            preserve_default=False,
        ),
    ]
