# Generated by Django 3.1.7 on 2022-03-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220307_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='urls',
        ),
    ]
