# Generated by Django 3.1.7 on 2022-03-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220316_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.langcharfieldshort'),
        ),
        migrations.AlterField(
            model_name='langcharfieldshort',
            name='en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='En'),
        ),
        migrations.AlterField(
            model_name='langcharfieldshort',
            name='ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ru'),
        ),
    ]
