# Generated by Django 3.1.7 on 2022-03-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220316_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangIntegerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.IntegerField(blank=True, default=0, verbose_name='En')),
                ('ru', models.IntegerField(blank=True, default=0, verbose_name='Ru')),
            ],
        ),
    ]
