# Generated by Django 3.1.7 on 2022-03-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_langintegerfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.langintegerfield'),
        ),
    ]
