# Generated by Django 3.1.7 on 2022-03-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20220317_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='name_new',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.langcharfieldshort'),
        ),
    ]
