# Generated by Django 3.1.7 on 2022-03-16 21:57

from django.db import migrations, models
import django.db.models.deletion


def migrate_categories(apps, schema_editor):
    Pattern = apps.get_model('api', 'Pattern')
    Lang = apps.get_model('api', 'LangCharFieldShort')
    for pattern in Pattern.objects.all():
        lang = Lang.objects.create(
            en='Empty',
            ru=pattern.name
        )
        lang.save()
        pattern.name_new = lang
        pattern.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_pattern_name_new'),
    ]

    operations = [
        migrations.RunPython(migrate_categories)
    ]
