# Generated by Django 3.1.7 on 2022-03-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_pattern_name_manual_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='name',
        ),
    ]
