# Generated by Django 3.1.7 on 2022-03-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20220317_2131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatternFile',
            new_name='PrivateFile',
        ),
    ]
