# Generated by Django 3.1.7 on 2022-03-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20220331_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='colors',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='api.privatefile', verbose_name='Цветовой подбор'),
        ),
    ]
