# Generated by Django 3.1.7 on 2022-05-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_pattern_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='index',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер в очереди'),
        ),
    ]
