# Generated by Django 3.1.7 on 2022-05-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_image_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['index', 'pk']},
        ),
    ]
