# Generated by Django 3.1.7 on 2022-08-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220815_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='token_verify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userVerify', to='api.token'),
        ),
    ]
